implement EmojiView and CustomViewGroup
tasktf2/PracticeApp pull request #1
Opened 2022-02-25 13:11 UTC by tasktf2

## Домашнее задание по лекции "View & ViewGroup"

 Нужно реализовать:

**1. Кастомную View для отображения Emoji реакции и кол-ва реакций**
- Можно использовать Emoji из unicode.
- Вьюха должна поддерживать 2 состояния и менять их по клику:
    - состояние когда emoji в сообщении выбрано нами и когда не выбрано. Для этой цели можно использовать state_selected. Как это сделать смотрите в семинаре
- Должна быть возможность задавать из кода emoji и кол-во реакций

**2. FlexBoxLayout, который способен располагать своих детей по следующему принципу:**
- Каждый ребенок помещается в строку
- Если следующий ребенок не влезает в эту строку, то необходимо перенести его на следующую
- Последним ребенком должен быть ImageView с иконкой + (с помощью нее можно будет в дальнейшем добавлять Emoji)

**3. Кастомную ViewGroup, которая отображает сообщение вместе с реакциями т.е.
у вас будет класс унаследованный от ViewGroup, который умеет отображать следующее:**
- Аватар пользователя
- Имя пользователя
- Текст сообщения
- Emoji-реакции(FlexBoxLayout с кастомными вьюхами внутри)

Ссылка на дизайн https://www.figma.com/file/98pEh8I134tHGYuN8POoxe/ZulipClone

2022-03-01 16:57 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/view/EmojiView.kt
> +            requestLayout()
в чем разница между requestLayout и invalidate?

2022-03-01 17:00 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/view/EmojiView.kt
> +        context.obtainStyledAttributes(attrs, R.styleable.EmojiView).apply {
можно ещё вот так
`context.withStyledAttributes(attrs, R.styleable.EmojiView, defStyleAttr) {
  }
 `

2022-03-01 17:05 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/view/EmojiView.kt
> +    fun getEmojiByUnicode(unicode: String): String {
лучше вынести в utils, во вью по максимуму должно лежать то, что относится к её отрисовке, этот метод больше утилитный

2022-03-01 17:06 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/view/EmojiView.kt
> +        paddingPaint.measureText("0", 0, "0".length)
лишнее

2022-03-01 17:09 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/view/EmojiView.kt
> +        } else emojiPaint.measureText(emoji, 0, emoji.length)
**if else** лучше юзать со всеми скобками, лучше читается

2022-03-01 17:09 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/view/EmojiView.kt
> +        else Toast.makeText(context,"Bottom navigation imitation",Toast.LENGTH_SHORT).show()
скобки if else

2022-03-01 17:16 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/view/EmojiView.kt
> +    var emoji: String = ""
лучше не просто emoji, а emojiCode что то такое

2022-03-01 17:18 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/view/EmojiView.kt
> +    var emojiCounter: Int = 0
лучше все публичные поля вынести повыше, вообще лучше так располагать поля и методы:

- public fields
- package-private fields
- protected fields
- private fields
- properties
- constructors
- override class methods
- override interface methods
- inline methods
- public methods
- package-private methods
- protected methods
- private methods
- abstract methods
- enums
- inner interface
- inner class
- companion objects

2022-03-01 17:20 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/view/EmojiView.kt
> +    private var colorSelected: Int = 0
цвета можно поменить аннотацией @ColorInt

2022-03-01 17:32 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/view/EmojiView.kt
> +        paddingPaint.measureText("0", 0, "0".length)
если я правильно понял, то measureText возвращает размер текста, возвращаемое значение никак не используется, поэтому строка лишняя

2022-03-01 17:34 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/view/EmojiView.kt
> +    private var emojiSize: Int
emojiSize используется один раз в качестве Float, лучше тогда и использовать тип Float, тогда не придётся ниже сто раз писать toInt

2022-03-01 17:41 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/view/EmojiView.kt
> +        else {
скобки if else

2022-03-01 17:45 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/view/EmojiView.kt
> +                width / 2f + textMargin - paddingPaint.textSize * (emojiCounter.toString().length - 1),
paddingPaint.textSize * (emojiCounter.toString().length - 1 повторяется, моэно вынести в переменную

2022-03-01 17:46 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/view/EmojiView.kt
> +                width / 2f + textMargin - paddingPaint.textSize * (emojiCounter.toString().length - 1),
width / 2 и height * 1.6 тоже

2022-03-01 17:46 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/view/EmojiView.kt
> +                width / 2f + textMargin - paddingPaint.textSize * (emojiCounter.toString().length - 1),
микрооптимизация

2022-03-01 17:52 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/view/FlexboxLayout.kt
> +//        setWillNotDraw(true)
поч закомментировано?

2022-03-01 17:54 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/view/FlexboxLayout.kt
> +                bottomMargin = context.dpToPx(10F)
лучше вынести в поле, тк методы onMeasure, onLayout, onDraw могут вызываться 100500 раз, поэтому в этих методах стоит избегать лишних вычислений и созданий экземпляров

2022-03-01 17:56 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/view/FlexboxLayout.kt
> +                currentWidth + childWidth > parentWidth -> {
всего 2 исхода, и одно исключает другое, поэтому можно обойтись if else

2022-03-01 17:58 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/view/FlexboxLayout.kt
> +                left + childWidth <= parentWidth -> {
тоже самое if else

2022-03-01 18:09 UTC, turik2304 requested changes
В целом ок, есть замечания по код-стайлу

2022-03-02 08:50 UTC, tasktf2 commented on app/src/main/java/com/setjy/practiceapp/view/EmojiView.kt
> +            requestLayout()
invalidate() асинхронно вызывает только onDraw(), а requestLayout() - все 3: onMeasure(), onLayout() и onDraw()

2022-03-02 08:50 UTC, tasktf2 commented on app/src/main/java/com/setjy/practiceapp/view/EmojiView.kt
> +        context.obtainStyledAttributes(attrs, R.styleable.EmojiView).apply {
Но суть от этого не меняется, верно?

2022-03-02 08:50 UTC, tasktf2 commented on app/src/main/java/com/setjy/practiceapp/view/EmojiView.kt
> +    var emoji: String = ""
изменил на emojiUnicode

2022-03-02 08:50 UTC, tasktf2 commented on app/src/main/java/com/setjy/practiceapp/view/EmojiView.kt
> +    var emojiCounter: Int = 0
Хорошая памятка так-то)

2022-03-02 08:51 UTC, tasktf2 commented on app/src/main/java/com/setjy/practiceapp/view/FlexboxLayout.kt
> +//        setWillNotDraw(true)
забыл раскомментировать

2022-03-02 08:54 UTC, tasktf2 commented
После изменений сделать новый коммит или как? Тут еще под reviewers имеется строчка: "Still in progress? Convert to draft". Как сделать лучше?

2022-03-02 09:24 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/view/EmojiView.kt
> +        context.obtainStyledAttributes(attrs, R.styleable.EmojiView).apply {
ага

2022-03-02 09:28 UTC, turik2304 approved these changes
эту ветку можешь мёржить

2022-03-02 15:11 UTC, merged