fix inflate
tasktf2/PracticeApp pull request #2
Opened 2022-03-06 18:09 UTC by tasktf2

2022-04-02 11:22 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/recycler/DiffCallback.kt
> +            oldItem is IncomingMessageUI && newItem is IncomingMessageUI -> {
по сути все **UI** итемы это **Data** классы, поэтому в этом методе можно просто **oldItem == newItem** для всех. Кста вопрос - когда и в каком порядке вызываются **areItemsTheSame** и **areContentsTheSame**?

2022-04-02 11:30 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/ChatFragment.kt
> +            val message = binding.etSend.text.toString()
1. а если editText пустой?
2. метод лучше сделать без экстеншена. Экстешн предполгает какое-то расширение функционала для ресивера. В данном случае это скорее частный случай, чем какой-то утилитный метод, который было бы удобно юзать несколько раз в виде экстеншена

2022-04-02 11:32 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/ChatFragment.kt
> +                    ivAdd.visibility = View.VISIBLE
можно юзать ivAdd.isVisible = true, так быстрее писать

2022-04-02 11:32 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/ChatFragment.kt
> +                    ivAdd.visibility = View.VISIBLE
можно юзать ivAdd.isVisible = true, так быстрее писать

2022-04-02 11:35 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/ChatFragment.kt
> +                item is OutgoingMessageUI -> item
в Zulip можно к своим сообщениям тоже крепить смайл, поэтому надо тут дописать для OutgoingMessageUI

2022-04-02 11:44 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/recycler/Adapter.kt
> +            notifyDataSetChanged()
submitList вычислит разницу в листах и применит изменения, а потом тут вызывается notifyDataSetChanged который нахрен опять всё возьмёт и перерисует, вообщем notifyDataSetChanged здесь не нуден

2022-04-02 11:47 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/recycler/items/BaseItems.kt
> +class SimpleItem(override val viewType: Int) : ViewTyped
вроде нигде не используется, можно удалить

2022-04-02 11:53 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/recycler/holders/EmojiViewHolder.kt
> +        view.setOnClickListener(click)
клик лучше сделать по аналогии с ChatHolderFactory, то есть сетить его не в самом вью-холдере, а в onCreateViewHolder. 
Сейчас клик возвращает View, давай сделаем так чтобы возвращал code

2022-04-02 11:56 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/recycler/bottom_sheet_fragment/BottomSheetFragment.kt
> +        val click: (View) -> Unit = { emoji: View ->
click лучше вынести в отдельный метод, типа onEmojiClick(code: String)...

2022-04-02 11:58 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/recycler/base/HolderFactory.kt
> +            R.layout.item_time_divider -> TimeDividerViewHolder(view)
этот вью-холдер относится же к чату, поэтому эту проверку можно вынести в ChatHolderFactory

2022-04-02 11:59 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/recycler/holders/TimeDividerViewHolder.kt
> +    private fun getTimeStamp(timeStamp: Long): String {
метод лучше вынести в util

2022-04-02 11:59 UTC, turik2304 commented on app/src/main/res/layout/custom_view_group.xml
> +    <!--Ниже определенно костыль-->
костыль можно выпилить

2022-04-02 12:03 UTC, turik2304 commented on app/src/main/res/layout/fragment_bottom_sheet.xml
> +        android:layout_height="306dp" />
можно не устанавливать точный размер, match_parent норм

2022-04-02 12:06 UTC, turik2304 commented on app/src/main/res/layout/fragment_chat.xml
> +        android:layout_marginBottom="69dp" />
вместо marginBottom лучше установить высоту как 0dp и привязать сверху к parent, а снизу к EditText

2022-04-02 12:12 UTC, turik2304 requested changes
В целом ок, надо доделать функционал по реакциям для исходящих сообщений и поправить клики в bottomSheetFragment, + правки по код-стайлу

2022-04-06 04:47 UTC, tasktf2 commented on app/src/main/java/com/setjy/practiceapp/recycler/DiffCallback.kt
> +            oldItem is IncomingMessageUI && newItem is IncomingMessageUI -> {
Если писать просто oldItem == newItem, то немного ругается Lint, поэтому явно написал сравнение.
Насчет вопроса: думаю, что сначала вызывается areItemsTheSame, а затем areContentsTheSame, когда необходимо проверить: изменилось ли содержимое, чтобы перерисовать, при set(newItems) = differ.submitList(newItems)

2022-04-06 04:47 UTC, tasktf2 commented on app/src/main/java/com/setjy/practiceapp/ChatFragment.kt
> +            val message = binding.etSend.text.toString()
А если editText пустой, то будет видна кнопка "добавить вложения", а не отправить сообщение, следовательно, пустое сообщение отправить не получится. Экстеншн убрал.

2022-04-06 04:49 UTC, tasktf2 commented on app/src/main/java/com/setjy/practiceapp/ChatFragment.kt
> +                item is OutgoingMessageUI -> item
Не очень то я рад был такому нововведению в самом конце, но все сделал и попрактиковался в пробросе нужных данных)

2022-04-06 04:50 UTC, tasktf2 commented on app/src/main/res/layout/fragment_bottom_sheet.xml
> +        android:layout_height="306dp" />
Если поставить match_parent, то придется делать отступ сверху, чтобы imageView была видна. Я не правильно думаю? Поправь)

2022-04-07 06:06 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/recycler/DiffCallback.kt
> +            oldItem is IncomingMessageUI && newItem is IncomingMessageUI -> {
да прост Supress аннотацию повесить и норм

2022-04-07 06:25 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/ChatFragment.kt
> +    private fun addReactionToMessage(messageId: String, emojiCode: String) {
в методах addReactionToMessage() и onEmojiClick() теперь одинаковый код в ветках when для Incoming и Outcoming сообщений, попробуй в методы вынести повторяющиеся блоки

2022-04-07 06:33 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/MainActivity.kt
> +        val bottomNavigationView = findViewById<BottomNavigationView>(R.id.bottom_nav_view)
чет с другой домашки вылезло тут, поправь на ChatFragment

2022-04-07 06:48 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/ChatFragment.kt
> +    private fun addReactionToMessage(messageId: String, emojiCode: String) {
второй вариант - объединить IncomingMessage и OutcomingMessage в sealed class типа так

```
sealed class MessageUI : ViewTyped {

    abstract val messageId: String
    abstract val message: String
    abstract val reactions: List<EmojiUI>
    abstract val userId: String

    data class IncomingMessageUI(
        override val messageId: String,
        override val message: String,
        override val reactions: List<EmojiUI>,
        override val viewType: Int = R.layout.item_msg_incoming,
        override val userId: String,
        val userName: String,
        val avatar: Int,
    ) : Message()

    data class OutgoingMessageUI(
        override val messageId: String,
        override val message: String,
        override val reactions: List<EmojiUI>,
        override val viewType: Int = R.layout.item_msg_outgoing,
        override val userId: String = DEFAULT_USER_ID
    ) : Message()

}
```

Тогда обе сущности будут объединены общими полями, и в ChatFragment будет достаточно один раз написать 
**item is MessageUI && item.messageId == messageId**

2022-04-07 06:55 UTC, turik2304 commented on app/src/main/res/layout/fragment_bottom_sheet.xml
> +        android:layout_height="306dp" />
<img width="587" alt="image" src="https://user-images.githubusercontent.com/73557404/162138024-7f531f32-2802-4c7c-ace8-5b5fdcfeeb03.png">
<img width="701" alt="image" src="https://user-images.githubusercontent.com/73557404/162138217-bb628245-7e66-4bb2-a29f-03d7e3603e1e.png">



Можно вот так сделать, чтобы наглядно видеть как будет отражаться

2022-04-07 06:57 UTC, turik2304 requested changes
пару замечаний ещё поправить и всё

2022-04-21 06:14 UTC, tasktf2 commented on app/src/main/java/com/setjy/practiceapp/ChatFragment.kt
> +    private fun addReactionToMessage(messageId: String, emojiCode: String) {
Наследование этих двух классов от базового было бы красивым, да. Но тут встает проблема: невозможно реализовать метод copy(). Тут либо делать списки реакций мутабельными, либо оставлять все как есть. Пока других решений не вижу, может, потом это как-то красиво обыграется)

2022-04-22 13:04 UTC, turik2304 approved these changes

2022-04-24 04:45 UTC, merged