add search logic in ChatFragment by using rxJava3
tasktf2/PracticeApp pull request #3
Opened 2022-06-28 14:52 UTC by tasktf2

## Домашнее задание по "Асинхронное взаимодействие + RxJava"

Нужно реализовать (используй стабовые данные):

**1. Все длительные операции выполняем асинхронно**
- Используем библиотеку [RxJava](https://github.com/ReactiveX/RxJava/tree/2.x)
- Запросы в сеть/базу данных и то, что сейчас симулирует эти запросы
- Поиск сообщений
- Вычислительные операции, вроде маппинга списков
- Работу с DiffUtils

**2. Реализовать поиск по списку сообщений**
- Поиск не должен повторно дергать методы выдачи результата если не был изменен поисковой запрос
- Поиск должен фильтровать пустые строки
- Поиск не должен дергать методы выдачи результата на каждый символ, если пользователь быстро вводит запрос в строку поиска.

2022-06-29 05:29 UTC, turik2304 commented on .idea/misc.xml
> +        <entry key="..\:/Users/setJy/StudioProjects/PracticeApp/app/src/main/res/drawable/bg_rounded_send.xml" value="0.1145" />
добавь директорию **.idea** в **gitignor**, эти файлы не нужны в репозитории

2022-06-29 05:42 UTC, turik2304 commented on app/build.gradle
> +    implementation 'io.reactivex.rxjava3:rxandroid:3.0.0'
в чем основное отличие между RxJava 1 и RxJava 2?

2022-06-29 05:53 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/ChatFragment.kt
> +                reactions = null
а если emptyList передать, норм всё будет?

2022-06-29 05:54 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/ChatFragment.kt
> +                reactions = null
просто думаю было бы надёжнее если бы поле было неналлабале, если реакций нет, то список пустой типа

2022-06-29 05:56 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/ChatFragment.kt
> +        Data.saveMessage(outgoingMessage)
save куда-то тоже обычно делается на IO потоке, ну здесь можно так оставить, потом видно будет где надо IO

2022-06-29 06:04 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/ChatFragment.kt
> +        }.withEndAction { view.isVisible = false }
а у этой анимации в конце start не надо вызывать?

2022-06-29 06:04 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/ChatFragment.kt
> +        if (text.isNullOrEmpty()) binding.ivSearchDelete.callOnClick()
if else?????

2022-06-29 06:05 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/ChatFragment.kt
> +            }
тут тоже мб start на анимацию нужен?

2022-06-29 06:08 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/ChatFragment.kt
> +    private fun setDeleteAnimationOnClick(view: View) {
по повойду нейминга, по сути это метод вызывающийся при клике, поэтому думаю лучше называть такие методы начиная с on***Click, типа onDeleteAnimationClick (слово Click впринципе можно опускать)

2022-06-29 06:08 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/ChatFragment.kt
> +    private fun setDeleteAnimation(text: Editable?) {
тоже нейминг onClick, смотри ниже

2022-06-29 06:12 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/ChatFragment.kt
> +        dispatchPublish(searchCounter--)
1. методы subscribeToUp, subscribeToDown не делают подписку, поэтому subscribe слово в нейминге не нужно
2. не обязательно создавать отдельный метод dispatchPublish, который используется только в этих двух "сабскрайбах"

2022-06-29 06:22 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/ChatFragment.kt
> +                searchList = adapter.items
searchList можно сделать локальной переменной а не полем

2022-06-29 06:22 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/ChatFragment.kt
> +                -1, 0 -> {
magic numbers

2022-06-29 06:24 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/ChatFragment.kt
> +                initSearchLogic()
на каждый клик происходит инициализация логики поиска, надо бы подумать как это сделать один раз

2022-06-29 06:24 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/ChatFragment.kt
> +                        emitter.onNext(text.toString().lowercase().trim())
Observable.just(...)?

2022-06-29 06:25 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/ChatFragment.kt
> +                                else "Найдено совпадений: ${list.size}"
curly braces

2022-06-29 06:26 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/ChatFragment.kt
> +                                searchCounter = -1 //start of search
-1 magic numbers

2022-06-29 06:27 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/ChatFragment.kt
> +        searchDisposable?.dispose()
вроде как disposable и searchDisposable можно заменить одним compositeDisposable

2022-06-29 06:31 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/ChatFragment.kt
> +                initSearchLogic()
суть - мы кладём что-то в publish, а на него смотрит observable. Тогда можно в одном месте, один раз подписаться на этот observable (сделать цепочку по обработке событий приходящих с publish)

2022-06-29 06:33 UTC, turik2304 commented on app/build.gradle
> +    implementation 'io.reactivex.rxjava3:rxandroid:3.0.0'
посмотри ещё в инете аналоги Subject'ов - Relay (PublishRelay, BehaviorRelay и тд), часто используются на практике, будет полезно почитать, по сути тоже самое но с нюансом

2022-06-29 06:36 UTC, turik2304 commented on app/src/main/res/drawable/ic_round_search_24.xml
> +    android:width="24dp" xmlns:android="http://schemas.android.com/apk/res/android">
почему в названиях драваблов round, они же не скругленные?

2022-06-29 06:42 UTC, turik2304 commented on app/src/main/res/layout/fragment_chat.xml
> +        android:id="@+id/search_background_bottom"
использование search_background_bottom можно избежать, в tv_search_results растянуть на всю ширину, добавить bg, и поиграться с отображением текста

2022-06-29 06:43 UTC, turik2304 commented on app/src/main/res/layout/fragment_chat.xml
> +        android:id="@+id/search_background_top"
про эту вьюшку я не понял, тоже бы избавиться от нёё

2022-06-29 06:49 UTC, turik2304 requested changes
в целом ок, основные замечания:
1. попробуй поиск сделать так, чтобы подписка была один раз в одном месте
2. не забудь диспоузить подписку в конце ЖЦ активити (тут уже сам разберись в какой момент ЖЦ нужно чистить подписку)
3. надо как-то обозначить все эти magic numbers, можно подумать в сторону enum или sealed class c object'ами, чтобы обозначить конкретные стейты, а не эти магические цифИрки
4. нейминг

Если поиск с одной подпиской не получится, оставляй так и делай след дз, потом созвонимся сделаем

2022-07-01 11:21 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/ChatFragment.kt
> +        private var searchCounter: Int = 0
кста, а почему в статике счётчик?

2022-07-14 11:51 UTC, tasktf2 commented on app/build.gradle
> +    implementation 'io.reactivex.rxjava3:rxandroid:3.0.0'
> в чем основное отличие между RxJava 1 и RxJava 2?
как я помню, в rxjava1 можно было класть null, а во второй сделали null-safety. Поправь, если не так

2022-07-14 11:52 UTC, tasktf2 commented on app/src/main/java/com/setjy/practiceapp/ChatFragment.kt
> +                reactions = null
> а если emptyList передать, норм всё будет?




да, все норм будет, поменял везде

2022-07-14 11:53 UTC, tasktf2 commented on app/src/main/java/com/setjy/practiceapp/ChatFragment.kt
> +        }.withEndAction { view.isVisible = false }
интересно, что без .start() тоже нормально работает

2022-07-14 11:54 UTC, tasktf2 commented on app/src/main/java/com/setjy/practiceapp/ChatFragment.kt
> +    private fun setDeleteAnimationOnClick(view: View) {
поправил на более понятные названия

2022-07-14 11:55 UTC, tasktf2 commented on app/src/main/res/drawable/ic_round_search_24.xml
> +    android:width="24dp" xmlns:android="http://schemas.android.com/apk/res/android">
импортировал из ресурс менеджера, там есть небольшое скругление, поэтому и генерировался суффикс раунд

2022-08-06 11:33 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/channels/ChannelsFragment.kt
> +class ChannelsFragment : Fragment() {
можно сюда передавать разметку, тогда не нужно переопределять onCreateView, типа
class ChannelsFragment : Fragment(R.layout.fragment_channels)

2022-08-06 11:38 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/channels/ChannelsHolderFactory.kt
> +                view.setOnClickListener {}
??

2022-08-06 11:40 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/recycler/holders/StreamItemViewHolder.kt
> +            onStreamClick?.invoke(item.streamName, arrow)
передавать imageView в клике не очень конечно, пока фиг с ним. Можно туду поставить, потом пофиксишь

2022-08-06 11:48 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/channels/PagerAdapter.kt
> +        StreamListFragment().newInstance(Page.SUBSCRIBED),
1. метод newInstance обычно делают статичным
2. внимательно посмотри что происходит на этой строчке

2022-08-06 11:50 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/channels/PagerAdapter.kt
> +    ALL_STREAMS(false)
тут по названию enum итема понятно какой из них subscribed,  а какой нет, мб убрать Boolean поле, а в местах использования проверять на инстанс

2022-08-06 12:17 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/channels/StreamListFragment.kt
> +    private var page: Page? = null
предлагаю сделать через lazy
private val page2: Page by lazy { arguments?.getSerializable(ARG_PAGE) as Page }

2022-08-06 12:17 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/channels/StreamListFragment.kt
> +    private var page: Page? = null
тогда в onCreate можно убрать инициализацию поля

2022-08-06 13:09 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/channels/StreamListFragment.kt
> +        Data.getStreamByName(streamNameFromClick)
в адаптере же уже лежит этот стрим, думаю можно обойтись без Rx

2022-08-06 13:13 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/channels/StreamListFragment.kt
> +                    arrow!!.isSelected = false
подумай на добавлением поля isExpanded в стрим, типа если раскрыли, то как нибудь stream.copy(isExpanded = true). Тогда в bind по этому полю можно выставлять isSelected.

Передача вьюшки в клик ведёт к утечкам. 
Плюс, если список чуть побольше, и если его промотать, то после перебиндинга в ресайклере будут мемы

2022-08-06 13:13 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/channels/StreamListFragment.kt
> +                adapter.notifyItemRangeChanged(topicIndex, topicIndex + currentTopics.size)
у тебя же diffUtil прикручен, зачем тут ещё notify?

2022-08-06 13:17 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/topic/SearchMessagesIterator.kt
> +        return index
можно в одну строку ++index

2022-08-06 13:18 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/topic/SearchMessagesIterator.kt
> +        return index
анал

2022-08-06 13:20 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/channels/StreamListFragment.kt
> +        Data.getStreams()
рх цепочку надо диспоузить, а то фрагмент потечёт

2022-08-06 13:30 UTC, turik2304 commented on app/src/main/res/navigation/bottom_nav.xml
> +<navigation xmlns:android="http://schemas.android.com/apk/res/android"
заебись что заюзал навигацию, я сам её никогда не юзал. Так то широко используется

2022-08-10 10:49 UTC, tasktf2 commented on app/src/main/java/com/setjy/practiceapp/channels/ChannelsHolderFactory.kt
> +                view.setOnClickListener {}
когда ребейсил старый код, не заметил этого. Раньше без этих листенеров клики не хотели пробрасываться (хотя должно было работать и без них)

2022-08-10 10:49 UTC, tasktf2 commented on app/src/main/java/com/setjy/practiceapp/recycler/holders/StreamItemViewHolder.kt
> +            onStreamClick?.invoke(item.streamName, arrow)
isExpanded решил эту проблему

2022-08-10 10:50 UTC, tasktf2 commented on app/src/main/java/com/setjy/practiceapp/channels/PagerAdapter.kt
> +        StreamListFragment().newInstance(Page.SUBSCRIBED),
да, чет не заметил. масло масленое получается))

2022-08-10 10:51 UTC, tasktf2 commented on app/src/main/java/com/setjy/practiceapp/channels/StreamListFragment.kt
> +                adapter.notifyItemRangeChanged(topicIndex, topicIndex + currentTopics.size)
старый код переносил, тогда еще дифутила не было

2022-08-10 11:01 UTC, tasktf2 commented
сделал поле isExpanded в стримАйтеме мутабельным, через .copy(isExpanded=) работать не желало корректно. баги пофиксил, изменение isSelected вьюшки сделал в бинде, пофиксил клики на стримы при поиске

2022-08-11 15:42 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/channels/StreamListFragment.kt
> +                if (page?.name == Page.SUBSCRIBED.name) {
можно просто page == Page.SUBSCRIBED

2022-08-11 15:50 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/channels/SearchResultsFilter.kt
> +                    item.isExpanded = !item.isExpanded
типа при поиске стрим развернётся или свернётся? чета вот эту строку не понял

2022-08-11 15:52 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/channels/StreamListFragment.kt
> +        fun newInstance(page: Page): StreamListFragment {
можно компактнее тупа так:

fun newInstance(page: Page) = StreamListFragment().apply {
            arguments = bundleOf(ARG_PAGE to page)
        }

2022-08-11 15:55 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/channels/StreamListFragment.kt
> +        fun newInstance(page: Page): StreamListFragment {
можно компактнее тупа так:
fun newInstance(page: Page) = StreamListFragment().apply {
            arguments = bundleOf(ARG_PAGE to page)
        }

2022-08-11 15:56 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/channels/StreamListFragment.kt
> +                        it is TopicItemUI && it.topicName == topic.topicName
трудно читается конечно, ну да шут с ним, отрефачим потом

2022-08-11 15:57 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/recycler/holders/StreamItemViewHolder.kt
> +        arrow = binding.ivArrow.apply {
поле **arrow** же сейчас не нужно

2022-08-11 16:05 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/recycler/items/StreamItemUI.kt
> +    var isExpanded: Boolean = false,
var конечно плохо, лучше стремиться к тому чтобы в модельках неизменяемые данные лежали

2022-08-12 07:47 UTC, tasktf2 commented on app/src/main/java/com/setjy/practiceapp/channels/SearchResultsFilter.kt
> +                    item.isExpanded = !item.isExpanded
по дефолту они свернуты. Там идет создание нового списка, по-другому не смог нормально реализовать. Так что при нажатии на поиск они становятся развернутыми

2022-08-12 07:50 UTC, tasktf2 commented on app/src/main/java/com/setjy/practiceapp/channels/StreamListFragment.kt
> +        fun newInstance(page: Page): StreamListFragment {
Верно, я просто на тот момент сгенерированным кодом воспользовался

2022-08-12 07:51 UTC, tasktf2 commented on app/src/main/java/com/setjy/practiceapp/recycler/items/StreamItemUI.kt
> +    var isExpanded: Boolean = false,
Да, понимаю это

2022-08-12 09:25 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/recycler/holders/StreamItemViewHolder.kt
> +            arrow.isSelected = item.isExpanded
лучше просто напрямую обращаться к вьюшке, а то записывать ссылку в переменную, а потом её передавать в клик как-то не оч

2022-08-12 15:18 UTC, turik2304 approved these changes

2022-08-12 18:55 UTC, merged