add clean arch, add mvi pattern to ProfileFragment
tasktf2/PracticeApp pull request #6
Opened 2022-11-02 17:52 UTC by tasktf2

Домашка по лекции архитектура

Нужно реализовать понравившуюся архитектуру: MVP или MVI ( MVVM нельзя использовать! Но можно оставить ViewModel)

Для MVI можно использовать библиотеки

    RxRedux https://github.com/freeletics/RxRedux
    TEA https://oolong-kt.org/

Задание со звездочкой: сделать сохранение состояния (для этой цели можно, например, использовать ViewModel)

2022-11-03 17:15 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/data/Constants.kt
> +    const val MESSAGES_TO_SAVE: Int = 50
константы разнести по соответствующим классам

2022-11-03 17:15 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/data/Constants.kt
> +    const val WRITE_TIMEOUT = 10L
тоже

2022-11-03 17:16 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/data/base/RemoteMapper.kt
> +interface RemoteMapper<M : Model, MR : ModelRemote, ME : ModelEntity> {
добавить in, out к параметрам, расположить в порядке in -> out

2022-11-03 17:18 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/data/base/ModelEntity.kt
> +open class ModelEntity
```suggestion
inerface ModelEntity
```

2022-11-03 17:18 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/data/base/ModelRemote.kt
> +open class ModelRemote
```suggestion
inerface ModelRemote
```

2022-11-03 17:20 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/data/local/storage/StreamStorage.kt
> +    private val database: ZulipDatabase = Room.databaseBuilder(
database в конструктор и через ДИ

2022-11-03 17:26 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/data/local/pref/Preferences.kt
> +interface Preferences {
заменить на паттерн LocalStorage, префы доставлять через DI. Текущие места использования заменить на DI зависимости.

2022-11-03 17:36 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/data/local/storage/StreamStorage.kt
> +        context.getString(R.string.database_name)
name базы передавать как константу а не ресурс

2022-11-03 17:38 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/data/model/MessageEntity.kt
> +package com.setjy.practiceapp.data.model
эту папку model можно перенести в local

2022-11-03 17:39 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/data/model/MessageEntity.kt
>      @PrimaryKey
PrimaryKey обычно первым идёт

2022-11-03 17:58 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/data/remote/NetworkService.kt
>          .addInterceptor(interceptor)
сущности NetworkService в DI

2022-11-03 18:02 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/domain/base/Model.kt
> +open class Model
interface

2022-11-03 18:11 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/domain/base/UseCase.kt
> +    fun execute(params: Params? = null): T
попробовать убрать nullable

2022-11-03 18:14 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/domain/model/MessageWithReactions.kt
> +        isOutgoingMessage = model.userId == AppPreferences().getOwnUserId()
префы лишние

2022-11-03 18:50 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/domain/usecase/user/GetOwnUserUseCase.kt
> +        }.map { mapper.mapToPresentation(it) }
добавить шедулеры для экзекютов, поставлять из через DI

2022-11-03 19:11 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/presentation/base/Item.kt
> +open class Item
- Разнести холдеры по экранам
- Итемы в стейт-файлах
- В Base оставить только Базу
- Вытащить Кастомные вьюшки в presentation
- Rename "view" -> "ui"
etc

2022-11-03 19:27 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/di/GlobalDI.kt
> +    private val profileReducer by lazy { LoadUserReducer() }
всё что относится к конкретному экрану убрать из GlobalDI, создавать их на этом конкретном экране

2022-11-03 19:34 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/presentation/view/profile/LoadUserStore.kt
> +    override fun bind(view: MviView<Action, State>): Disposable {
- вынести реализацию wire и bind в abstract Store
- abstract Store сделать обычным классом
- LoadUserStore удалить
- Собирать Store руками во вью-модели
- Зависимости в Store передаются через зависимости вью-модели
- Зависимости вью-модели передаются через ViewModelFactory + DI

2022-11-03 19:35 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/presentation/view/profile/LoadUserStore.kt
> +    override fun bind(view: MviView<Action, State>): Disposable {
завести BaseAction, BaseState, BaseEffect

2022-11-03 19:37 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/presentation/view/profile/LoadUserMiddleware.kt
> +        actions.filter { it is Action.LoadingOwnUser }
ofType

2022-11-03 19:47 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/presentation/view/profile/LoadUserMiddleware.kt
> +class LoadUserMiddleware(private val getOwnUserUseCase: GetOwnUserUseCase) :
передать абстракцию UseCase и запихать через DI

2022-11-03 20:22 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/presentation/view/base/MviView.kt
> +    val _actions: PublishRelay<A>
избавиться от actions и _actions. Завесит fun accept в Store и вью-модели. Прокидывать действия напрямую в Publish стора через этот метод

2022-11-03 20:38 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/presentation/view/profile/UiEffect.kt
> +sealed class UiEffect {
Реализовать эффекты в Store по аналогии с actions.
Добавить reduceToEffect используя Optional

2022-11-03 20:41 UTC, turik2304 requested changes
Поправить

2022-11-06 12:34 UTC, tasktf2 commented on app/src/main/java/com/setjy/practiceapp/presentation/base/Item.kt
> +open class Item
остальные итемы разнесу как появятся новые стейты

2022-11-06 12:35 UTC, tasktf2 commented on app/src/main/java/com/setjy/practiceapp/presentation/view/profile/LoadUserStore.kt
> +    override fun bind(view: MviView<Action, State>): Disposable {
посмотришь, я там создание всего для mvi сделал во ВьюМодэлФэктори и юзкейс из DI подцепил

2022-11-06 12:36 UTC, tasktf2 commented on app/src/main/java/com/setjy/practiceapp/presentation/view/profile/UiEffect.kt
> +sealed class UiEffect {
эффекты закину как понадобятся, а то для профиля оверхэд по-моему

2022-11-06 12:39 UTC, tasktf2 commented
у меня вот вопрос. Везде имеется костыльная проверка на всех обсах на проверку ошибки на отсутствие инета. Там есть таймер 10L,  мне в этом случае куда пихать эту чиселку?

2022-11-08 14:55 UTC, turik2304 requested changes
доделать peoples

2022-11-08 15:08 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/presentation/ui/people/middleware/SearchUsersMiddleware.kt
> +            .withLatestFrom(state) { action, lastState ->
debounce+distinct

2022-11-08 15:12 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/presentation/ui/people/PeopleFragment.kt
> +        binding.etSearch.addTextChangedListener { text ->
initUserSearch дёргается на каждый render, поправить

2022-11-08 15:13 UTC, turik2304 commented on app/src/main/java/com/setjy/practiceapp/presentation/ui/people/PeopleFragment.kt
> +    private var disposable: CompositeDisposable = CompositeDisposable()
лишний

2022-11-08 15:16 UTC, turik2304 requested changes
поправить миноры и смёржить, след ПР со стримами

2022-11-09 06:49 UTC, merged